CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS public.scrobbles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_name text NOT NULL,
    artist_name text NOT NULL,
    album_name text,
    played_at timestamptz NOT NULL UNIQUE,
    spotify_id text,
    created_at timestamptz DEFAULT now(),
    image_url text,
    album_id text,
    artist_id text,
    artist_genres text[],
    mood_label text,
    accent_color text
);

CREATE INDEX IF NOT EXISTS idx_album_search
ON public.scrobbles USING gin (album_name public.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_artist_search
ON public.scrobbles USING gin (artist_name public.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_played_at
ON public.scrobbles (played_at DESC);

CREATE INDEX IF NOT EXISTS idx_scrobbles_album_id
ON public.scrobbles (album_id);

CREATE INDEX IF NOT EXISTS idx_scrobbles_artist_id
ON public.scrobbles (artist_id);

CREATE INDEX IF NOT EXISTS idx_scrobbles_spotify_id
ON public.scrobbles (spotify_id);

CREATE INDEX IF NOT EXISTS idx_track_search
ON public.scrobbles USING gin (track_name public.gin_trgm_ops);
